[project]
name = "heart-disease-detection"
version = "1.0.0"

requires-python = ">= 3.10.0"

dependencies = [
    "numpy >= 2.2.1",
    "pandas >= 2.2.3",
    "scikit-learn >= 1.6.0",
    "matplotlib >= 3.9.4"
]

[project.scripts]
hd = "regression_code:main"